var attributeTypes = {
"3":{"unitname":"Hitpoints","displayname":"Item Damage","displayunit":"HP","categoryname":"Miscellaneous"},
"4":{"unitname":"Mass","displayname":"Mass","displayunit":"kg","categoryname":"Structure"},
"9":{"unitname":"Hitpoints","displayname":"Structure Hitpoints","displayunit":"HP","categoryname":"Structure"},
"11":{"unitname":"MegaWatts","displayname":"Powergrid Output","displayunit":"MW","categoryname":"Fitting"},
"12":{"unitname":"Fitting slots","displayname":"Low Slots","displayunit":"","categoryname":"Fitting"},
"13":{"unitname":"Fitting slots","displayname":"Medium Slots","displayunit":"","categoryname":"Fitting"},
"14":{"unitname":"Fitting slots","displayname":"High Slots","displayunit":"","categoryname":"Fitting"},
"18":{"unitname":"capacitor units","displayname":"charge","displayunit":"GJ","categoryname":"NULL"},
"19":{"unitname":"","displayname":"powerToSpeed","displayunit":"","categoryname":"NULL"},
"21":{"unitname":"","displayname":"warpFactor","displayunit":"","categoryname":"Miscellaneous"},
"37":{"unitname":"Acceleration","displayname":"Maximum Velocity","displayunit":"m/sec","categoryname":"Speed"},
"38":{"unitname":"Volume","displayname":"Capacity","displayunit":"m3","categoryname":"Structure"},
"48":{"unitname":"Teraflops","displayname":"CPU Output","displayunit":"tf","categoryname":"Fitting"},
"49":{"unitname":"Teraflops","displayname":"CPU Load","displayunit":"tf","categoryname":"NULL"},
"55":{"unitname":"Milliseconds","displayname":"Capacitor Recharge time","displayunit":"s","categoryname":"Capacitor"},
"70":{"unitname":"Multiplier","displayname":"Inertia Modifier","displayunit":"x","categoryname":"Speed"},
"76":{"unitname":"Length","displayname":"Maximum Targeting Range","displayunit":"m","categoryname":"Targeting"},
"79":{"unitname":"Milliseconds","displayname":"scanSpeed","displayunit":"s","categoryname":"Targeting"},
"101":{"unitname":"Hardpoints","displayname":"Launcher Hardpoints","displayunit":"hardpoints","categoryname":"Fitting"},
"102":{"unitname":"Hardpoints","displayname":"Turret Hardpoints","displayunit":"hardpoints","categoryname":"Fitting"},
"109":{"unitname":"Inverse Absolute Percent","displayname":"Structure Kinetic Damage Resistance","displayunit":"%","categoryname":"Structure"},
"110":{"unitname":"Inverse Absolute Percent","displayname":"Structure Thermal Damage Resistance","displayunit":"%","categoryname":"Structure"},
"111":{"unitname":"Inverse Absolute Percent","displayname":"Structure Explosive Damage Resistance","displayunit":"%","categoryname":"Structure"},
"113":{"unitname":"Inverse Absolute Percent","displayname":"Structure EM Damage Resistance","displayunit":"%","categoryname":"Structure"},
"124":{"unitname":"","displayname":"mainColor","displayunit":"","categoryname":"NULL"},
"129":{"unitname":"","displayname":"maxPassengers","displayunit":"","categoryname":"NULL"},
"136":{"unitname":"","displayname":"uniformity","displayunit":"","categoryname":"Shield"},
"153":{"unitname":"","displayname":"warpCapacitorNeed","displayunit":"","categoryname":"NULL"},
"161":{"unitname":"Volume","displayname":"Volume","displayunit":"m3","categoryname":"Structure"},
"162":{"unitname":"","displayname":"radius","displayunit":"","categoryname":"NULL"},
"182":{"unitname":"typeID","displayname":"Primary Skill required","displayunit":"typeID","categoryname":"Required Skills"},
"192":{"unitname":"","displayname":"Maximum Locked Targets","displayunit":"","categoryname":"Targeting"},
"208":{"unitname":"attributePoints","displayname":"RADAR Sensor Strength","displayunit":"points","categoryname":"Targeting"},
"209":{"unitname":"attributePoints","displayname":"Ladar Sensor Strength","displayunit":"points","categoryname":"Targeting"},
"210":{"unitname":"attributePoints","displayname":"Magnetometric Sensor Strength","displayunit":"points","categoryname":"Targeting"},
"211":{"unitname":"attributePoints","displayname":"Gravimetric Sensor Strength","displayunit":"points","categoryname":"Targeting"},
"217":{"unitname":"","displayname":"propulsionGraphicID","displayunit":"","categoryname":"Graphics"},
"246":{"unitname":"","displayname":"gfxBoosterID","displayunit":"","categoryname":"Graphics"},
"263":{"unitname":"Hitpoints","displayname":"Shield Capacity","displayunit":"HP","categoryname":"Shield"},
"264":{"unitname":"","displayname":"shieldCharge","displayunit":"","categoryname":"NULL"},
"265":{"unitname":"Hitpoints","displayname":"Armor Hitpoints","displayunit":"HP","categoryname":"Armor"},
"267":{"unitname":"Inverse Absolute Percent","displayname":"Armor EM Damage Resistance","displayunit":"%","categoryname":"Armor"},
"268":{"unitname":"Inverse Absolute Percent","displayname":"Armor Explosive Damage Resistance","displayunit":"%","categoryname":"Armor"},
"269":{"unitname":"Inverse Absolute Percent","displayname":"Armor Kinetic Damage Resistance","displayunit":"%","categoryname":"Armor"},
"270":{"unitname":"Inverse Absolute Percent","displayname":"Armor Thermal Damage Resistance","displayunit":"%","categoryname":"Armor"},
"271":{"unitname":"Inverse Absolute Percent","displayname":"Shield EM Damage Resistance","displayunit":"%","categoryname":"Shield"},
"272":{"unitname":"Inverse Absolute Percent","displayname":"Shield Explosive Damage Resistance","displayunit":"%","categoryname":"Shield"},
"273":{"unitname":"Inverse Absolute Percent","displayname":"Shield Kinetic Damage Resistance","displayunit":"%","categoryname":"Shield"},
"274":{"unitname":"Inverse Absolute Percent","displayname":"Shield Thermal Damage Resistance","displayunit":"%","categoryname":"Shield"},
"277":{"unitname":"","displayname":"requiredSkill1Level","displayunit":"","categoryname":"Required Skills"},
"283":{"unitname":"Volume","displayname":"Drone Capacity","displayunit":"m3","categoryname":"Drones"},
"351":{"unitname":"Percentage","displayname":"Optimal Range Bonus","displayunit":"%","categoryname":"Bonuses"},
"422":{"unitname":"Level","displayname":"Tech Level","displayunit":"Level","categoryname":"Miscellaneous"},
"479":{"unitname":"Milliseconds","displayname":"Shield recharge time","displayunit":"s","categoryname":"Shield"},
"482":{"unitname":"capacitor units","displayname":"Capacitor Capacity","displayunit":"GJ","categoryname":"Capacitor"},
"484":{"unitname":"","displayname":"shieldUniformity","displayunit":"","categoryname":"Shield"},
"524":{"unitname":"","displayname":"armorUniformity","displayunit":"","categoryname":"Armor"},
"525":{"unitname":"","displayname":"structureUniformity","displayunit":"","categoryname":"Structure"},
"552":{"unitname":"Length","displayname":"Signature Radius","displayunit":"m","categoryname":"Targeting"},
"564":{"unitname":"Millimeters","displayname":"Scan Resolution","displayunit":"mm","categoryname":"Targeting"},
"600":{"unitname":"Multiplier","displayname":"Warp Speed Multiplier","displayunit":"x","categoryname":"Miscellaneous"},
"633":{"unitname":"Level","displayname":"Meta Level","displayunit":"Level","categoryname":"Miscellaneous"},
"661":{"unitname":"","displayname":"maxDirectionalVelocity","displayunit":"","categoryname":"NULL"},
"662":{"unitname":"","displayname":"minTargetVelDmgMultiplier","displayunit":"","categoryname":"NULL"},
"734":{"unitname":"","displayname":"shipBonusCD1","displayunit":"","categoryname":"NULL"},
"735":{"unitname":"","displayname":"shipBonusCD2","displayunit":"","categoryname":"NULL"},
"793":{"unitname":"","displayname":"shipBonusPirateFaction","displayunit":"","categoryname":"NULL"},
"1132":{"unitname":"attributePoints","displayname":"Calibration","displayunit":"points","categoryname":"Miscellaneous"},
"1137":{"unitname":"Fitting slots","displayname":"Rig Slots","displayunit":"","categoryname":"Fitting"},
"1154":{"unitname":"Hardpoints","displayname":"Upgrade Hardpoints","displayunit":"hardpoints","categoryname":"Miscellaneous"},
"1178":{"unitname":"","displayname":"heatCapacityHi","displayunit":"","categoryname":"NULL"},
"1179":{"unitname":"","displayname":"heatDissipationRateHi","displayunit":"","categoryname":"NULL"},
"1196":{"unitname":"","displayname":"heatDissipationRateMed","displayunit":"","categoryname":"NULL"},
"1198":{"unitname":"","displayname":"heatDissipationRateLow","displayunit":"","categoryname":"NULL"},
"1199":{"unitname":"","displayname":"heatCapacityMed","displayunit":"","categoryname":"NULL"},
"1200":{"unitname":"","displayname":"heatCapacityLow","displayunit":"","categoryname":"NULL"},
"1224":{"unitname":"","displayname":"heatGenerationMultiplier","displayunit":"","categoryname":"NULL"},
"1259":{"unitname":"","displayname":"Heat Attenuation","displayunit":"","categoryname":"Miscellaneous"},
"1261":{"unitname":"","displayname":"heatAttenuationMed","displayunit":"","categoryname":"Miscellaneous"},
"1262":{"unitname":"","displayname":"heatAttenuationLow","displayunit":"","categoryname":"Miscellaneous"},
"1271":{"unitname":"Drone bandwidth","displayname":"Drone Bandwidth","displayunit":"Mbit/sec","categoryname":"Drones"},
"1281":{"unitname":"","displayname":"Ship Warp Speed","displayunit":"","categoryname":"Miscellaneous"},
"1547":{"unitname":"Sizeclass","displayname":"Rig Size","displayunit":"1=small 2=medium 3=l","categoryname":"Miscellaneous"},
"1768":{"unitname":"","displayname":"typeColorScheme","displayunit":"","categoryname":"Miscellaneous"}
};